### ISSUE TITLE
Add xarray support to hyperslicer

### ISSUE THREAD

**Issue by ianhi** [ianhi/mpl-interactions#134]
### Problem
Hyperslicer should support xarray natively and read names and such for the sliders via the xarray info.

### Proposed Solution
 @jrussell25 has  most of implementation of this. We should bulid on that. I'm opening this just so there is a coherent place to keep track of it and to note things like this:
Currently hyperslicer forces all arrays to be loaded into memory due to this line: https://github.com/ianhi/mpl-interactions/blob/050c989557aecbcb1077306a7b325159ea3c8ecd/mpl_interactions/generic.py#L574 we will need to avoid that otherwise v bad news when big data.

**Comment by jrussell25** [comment]
I dont know how to handle the out of memory case. Is that really something we need to support? 

My only idea is to call `.load()` on the xarray slice when you call imshow. but maybe theres a better way. I also dont know how you did caching for ode stuff but something like that would probably be helpful if were going to go down this road.

**Comment by jrussell25** [comment]
This will be closed by #138

**Comment by ianhi** [comment]
fixed by #138
