### ISSUE TITLE
include scatter spectra picker?

### ISSUE THREAD

**Issue by ianhi** [ianhi/mpl-interactions#140]
### Problem
Just made this maybe useful thing with @kobayashikirschvink that allows for selecting a point in a scatter plot and plotting from data indexed by it onto a second data source. This seems generically useful enough to merit inclusion. At least maybe it is, idk...(@jrussell25 thoughts?)

### Proposed Solution
Here is the code and an example:
```python
import numpy as np
import matplotlib.pyplot as plt


def scatter_spectra_selector(X, Y, spectra, axes=None, figsize=(12, 5), pickradius=5, **kwargs):
    """
    X : array-like 1D
        X coordinates of the scatter plot
    Y : array-like 1D
        Y coordinates of the scatter plot
    spectra : array-like 2D
        should have shape (N spectra, length of spectra)
    ax : tuple of matplotlib axes, default: None
        axes on which to plot, If providing you need two axes. i.e. `(ax1, ax2)`
        if not provided then a new figure will be created
    figsize : tuple of float, default: (12, 5)
        figsize to use if this function is creating the figure
    pickradius : float, default: 5
        the pickradius to use for the lines. Make it smaller to be able to click
        more precisely.
    **kwargs:
        all other kwargs will passed through to the plot command

    """
    if axes is None:
        fig, axes = plt.subplots(1, 2, figsize=figsize)
    else:
        fig = axes.get_figure()
    scat = axes[0].scatter(X, Y, **kwargs, picker=True)

    (line,) = axes[1].plot([], [])
    spectra_x = np.arange(spectra.shape[1])

    def onpick(event):
        if event.mouseevent.button not in [2, 3]:
            # `event.button in [2,3]` checks for both right and middle clicks due
            #  https://github.com/matplotlib/matplotlib/pull/18172 not being included in matplotlib < 3.4
            idx = event.ind[0]
            line.set_data(spectra_x, spectra[idx])
            axes[1].set_title(idx)
            axes[1].relim()
            axes[1].autoscale_view()

    fig.canvas.mpl_connect("pick_event", onpick)
    return axes, scat
```
```python
# create fake data
N = 10
spectra = np.random.randn(N, 100).cumsum(axis=-1)  # random walkers as fake spectra
umap = np.random.randn(N, 2)
gfp = np.random.randn(N)

axes, scat = scatter_spectra_selector(umap[:, 0], umap[:, 1], spectra, c = gfp)
zoom_factory(axes[0])
ph2 = panhandler(axes[1].get_figure())
fig = axes[0].get_figure().colorbar(scat, ax=axes[0])
```
![Peek 2020-11-19 00-06](https://user-images.githubusercontent.com/10111092/99623898-16253780-29fb-11eb-886d-05612f7c8fce.gif)
This would need to be cleaned up a bit for inclusion probably and the api thought through a bit more, but it's mostly there.

**Comment by ianhi** [comment]
My confusion is that this seems reasonably useful, but is also easy enough to implement on ones own. Though honestly it took me awhile to get right, so maybe it's not that easy.

**Comment by kmdalton** [comment]
i for one have no idea how to implement this. how hard would it be to make the right hand plot an image or scatter plot?

**Comment by ianhi** [comment]
@kmdalton it wouldn't be hard to implement that. The difficulty there would be coming up with a reasonable api and reasonable function name.

**Comment by kmdalton** [comment]
`metascatterplot`?

**Comment by kmdalton** [comment]
and maybe you provide a closure for generating the right hand plot contingent on a point index?

**Comment by ianhi** [comment]
oh hmm. I was imagining a function that handled the plotting for you, but I like the idea of allowing the user to specify plotting. Simplifies the nightmare of passing plotting kwargs through. Maybe the best choice is to provide multiple functions that span the space of the customizability/ease of use tradeoff.

So we'd make the following functions:
**1.**
User provides a closure that handles plotting
```python
X = ...
Y = ...
data = .....
def f(ax, index):
   ax.cla()
   ax.plot....

metascatter_function(X,Y, f)
```
**2.**
user provides data and plotting is handled for them
```python
X = ...
Y = ...
data = .....

metascatter_function(X,Y, data, plottype='hist')
```

**Comment by kmdalton** [comment]
It sounds like you're on the right track there. I am not gonna say I'd use this, but I can imagine it being useful. It would also make your spectral example a special case. 

You could imagine generally useful special cases along the lines of the left plot being a low dimensional embedding like the first 2 PCs of a data matrix. The right axis could be a line plot of the column of data underlying the selected point.

**Comment by ianhi** [comment]
oooooh. or maybe a better thing to do is to leverage the existing `controller` object. The above proposal is very similar to how the pyplot module started out working. But the big limitation is that if you want to connect multiple plots it's basically impossible. 

So the idea could be to generalize the kinds of controls that the `controller` object can hold. Currently it only knows how to have ipywidgets widgets or matplotlib widgets. But I think it could also treat a scatter plot selection callback in a similar way. So that this would be possible:

```python
from mpl_interactions import ipyplot as iplt
from mpl_interactions.dataselection import scatter_selector

fig, axes = plt.subplots(1,2)
controls = scatter_selector(X,Y, ax=axes[0], name='spot')
def f(index):
   return data[i]
iplt.imshow(f, controls=controls['spot'], ax=axes[1])
```

or even make an `indexor` function that would create that `f` function for you. Something like:
```python
def indexor(idx, data):
   def f(idx):
       return data[idx]
   return f
```

**Comment by ianhi** [comment]
> You could imagine generally useful special cases along the lines of the left plot being a low dimensional embedding like the first 2 PCs of a data matrix. The right axis could be a line plot of the column of data underlying the selected point.

right on - this is exactly the original motivation from koseki.

**Comment by ianhi** [comment]
I think the `indexor` function is probably generically useful, and the `scatter_selector` shouldn't return a controls object, rather it should act as a matplotlib widget (maybe even explicitly subclass). So that it would work like this:
```python
from mpl_interactions import ipyplot as iplt
from mpl_interactions.dataselection import scatter_selector

fig, axes = plt.subplots(1,2)
spot_index_widget = scatter_selector(X,Y, ax=axes[0])

controls = iplt.imshow(indexor(data), index=spot_index_widget, ax=axes[1])
```

**Comment by ianhi** [comment]
I think this solution of making a new widget is the most consistent with the library and will have the least api headaches. The trouble is it will require a bit of rework on the `controller` object to allow mixing ipywidgets widgets and matplotlib widgets.

**Comment by ianhi** [comment]
I think that for scatter selector to work in a way that makes any sense and isn't a nightmare to document there need to be two versions. `scatter_selector_values` and `scatter_selector_index`. Where the former would return x,y pairs and the latter the index of the selected point. 

Also these scatter selectors should accept functions for X and Y etc like `iplt.scatter` does. Or maybe that's too much of a nightmare. That's a weird mixing of concerns where controls can control other controls.
