### ISSUE TITLE
Add drop-down menu for class in image_segmenter

### ISSUE THREAD

**Issue by rkube** [ianhi/mpl-interactions#175]
Hi,
I'm working with image_segmenter and was wondering if it is possible to select the class using a drop-down menu instead of running a new cell every time one needs to change the class.

**Comment by ianhi** [comment]
Hi @rkube that's a great idea. I've been tracking the general case (of controlling all aspects of the segmenter) over in https://github.com/ianhi/mpl-interactions/issues/99 so I'm going to close this to keep things contained. But please feel free to keep the discussion going over there.

**Comment by ianhi** [comment]
I mentioned this in the other thread - but to reduce the hassle of finding it for future people coming accross this. If all you want is a dropdown it's pretty simple to add one manually using ipywidgets:

```python
import ipywidgets as widgets

N_classes = 3
class_selector = widgets.Dropdown(options=list(range(N_classes)), description="class")


def change_class(change):
    multi_class_segmenter.current_class = class_selector.value


class_selector.observe(change_class, names="value")
multi_class_segmenter = image_segmenter(image, nclasses=3, mask_alpha=0.76)
display(class_selector)
display(multi_class_segmenter)
```

**Comment by rkube** [comment]
Neat, thanks!
