### ISSUE TITLE
Switch Docs to MYST

### ISSUE THREAD

**Issue by ianhi** [ianhi/mpl-interactions#206]
### Problem
MYST is good stuff and probably the future so we should move to it.

### Suggested Improvement
Swap to MYST. See explanation from @redeboer at https://github.com/ianhi/mpl-interactions/pull/203#issuecomment-884417143

**Comment by redeboer** [comment]
The conversion can be done easily with https://rst-to-myst.readthedocs.io. I could get do that later this week, have done that transition before.
