### ISSUE TITLE
Detect and run doctests with pytest

### ISSUE THREAD

**Issue by redeboer** [ianhi/mpl-interactions#210]
When running `pytest --collect-only` (which happens for instance when you want to explore the tests in VSCode), some matplotlib plots are created. This means there is some code that is not within a (test) function, which slows down test discovery.

**Comment by ianhi** [comment]
Does this happen when you run in the terminal? Looking through the tests I don't see anywhere this would happen. When I run `pytest --collect-only` from the terminal no figures are created and it claims to have collected all in `.41` seconds.

**Comment by redeboer** [comment]
Ohh hang on, sorry :expressionless: It's after I added the doctest-modules flag that some scripts were run...
So was a bit too fast posting this. Still, it would be nice to let pytest detect any potential doctests without error.
