### ISSUE TITLE
panhandler doesn't work when you call from another function

### ISSUE THREAD

**Issue by gztony1227** [ianhi/mpl-interactions#228]
Hi Ian,
Long time, I hope things are going well at SEAS.
I had a chance to try out your mpl interactions. I couldn't get this part working after 2 hours and maybe you know what the bug might be.
When I try to call panhandler from another py file by giving the correct fig and ax, it wouldn't work. On the opposite, if I directly call it in the same py file for plotting, it will work. This has limitation because in the future it's nice to have one function to take care of all interactions and plotting related customization. Right now I cannot include panhandler.
here is the dropbox link of codes I made. Should make your life easy to quick see what i'm saying:
https://www.dropbox.com/t/ikyWUZabCLVYc9Lu

video proof:
https://capture.dropbox.com/Mt1zc6zVfWx2KQxy
The link expires in 7 days. If you need it again, send me an email.

thanks,
Tony

### Bug report

**Bug summary**

**Code for reproduction**

**Expected outcome**

**Version Info**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ianhi** [comment]
Hi Tony so happy to see you using this library!

This is an issue of variable scoping in python, In your first example `panhandler` is declared in the global scope so the object never gets garbage collected and the interaction remains for the entire run time of the script. But once you put it inside of a function like this

```python
```

**Comment by ianhi** [comment]
I can see how the documentation for this can be confusing (https://mpl-interactions.readthedocs.io/en/stable/examples/zoom-factory.html#scrolling-and-panning) because it simply says:

> You need to make sure to assign the panhanler to a variable otherwise it will be garbage collected and will not work.

Do you have any suggestions for improving or adding to that that would have helped you?


-----

If you're able to share what you're using this for I'd be super curious to know about it! Also happy to glance over any open source code that uses this library to see if I have any suggestions for improving it.

**Comment by gztony1227** [comment]
Hi Ian,
This is very helpful. It works. I was aware of the scoping you mentioned.
If you look at what I wrote then you may realized that disconnect_zoom = zoom_factory(ax, base_scale=1.4) is also there but zoom factory works just fine without returns. The only distinction in the moment I can think of is zoom_factory is a function and panhandler is a class. If you know python collects garbage differently regarding both, please let me know and that will be great to learn. Because zoom factory worked, I never had a thought to return panhandler object. Also I'm more used to matlab so I know both lines should work in matlab without returns.
To further proof there is a distinction, besides zoom_factory and panhandler, I also have a function from other sources called "_rectangle_selector_factory(fig, ax)". It also works well like zoom factory without returns. Anyway, there are always mysteries too deep and too time consuming to understand in all computer languages. My problem is solved so thank you!

**Comment by ianhi** [comment]
> The only distinction in the moment I can think of is zoom_factory is a function and panhandler is a class.
> If you know python collects garbage differently regarding both, please let me know and that will be great to learn. Because zoom factory worked, I never had a thought to return panhandler object. 


This is sort of the distinction. The return value of zoom_factory actually only knows how to disconnect the zooming function:
https://github.com/ianhi/mpl-interactions/blob/aa3b1bcc85332eda4d098e7ad16bea16615f9424/mpl_interactions/generic.py#L294-L298

The real work in zoom factory is done by a function that gets attached to those axes as a callback

https://github.com/ianhi/mpl-interactions/blob/aa3b1bcc85332eda4d098e7ad16bea16615f9424/mpl_interactions/generic.py#L248
I think the deeper difference is that for zooming the mechanics are done using  just use a single callback function - 
https://github.com/ianhi/mpl-interactions/blob/aa3b1bcc85332eda4d098e7ad16bea16615f9424/mpl_interactions/generic.py#L292


and matplotlib will keep a reference to it which keeps it alive.


Whereas for the panning you actually call the constructor of the `panhandler` object so if you don't explicitly hang on to it then python will drop it thinking that you no longer want it.


----

Anyway glad we could get it sorted!
