### ISSUE TITLE
Didn't find the package using Mamba

### ISSUE THREAD

**Issue by ivaquero** [ianhi/mpl-interactions#249]
### Bug report

**Code for reproduction**

mamba install mpl-interactions=0.22

**Actual outcome**

Encountered problems while solving:
  - package mpl-interactions-0.22.0-pyhd8ed1ab_0 requires python >=3.6,<3.10, but none of the providers can be installed
  - 

**Version Info**
  * Operating system: MacOS 12.4 Monterey M1
  * Matplotlib version: 3.5.2
  * Python version: 3.10.5

**Comment by ianhi** [comment]
Ahhh it looks like I removed the upper python limit on the pypi package but conda-forge also will need an update. I'll look into that

**Comment by ianhi** [comment]
It ought to work now. please let me know if it doesn't

(didn't realize i could autoclose an issue across repos like that)
