### ISSUE TITLE
sliders not showing with ipywidgets 8.0.1

### ISSUE THREAD

**Issue by jubrau** [ianhi/mpl-interactions#255]
### Bug report

**Bug summary**

After freshly installing using `pip install mpl_interactions[jupyter]`, sliders generated by `plot` or `hyperslice` do not appear in the generated figure anymore.

**Code for reproduction**
```
conda create -n test python=3.9
conda activate test
pip install mpl_interactions[jupyter]
```

(installs `ipywidgets==8.0.1`)

```python
import mpl_interactions.ipyplot as iplt
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, np.pi, 100)
tau = np.linspace(0.5, 10, 100)

def f1(x, tau, beta):
    return np.sin(x * tau) * x * beta
def f2(x, tau, beta):
    return np.sin(x * beta) * x * tau


fig, ax = plt.subplots()
controls = iplt.plot(x, f1, tau=tau, beta=(1, 10, 100), label="f1")
iplt.plot(x, f2, controls=controls, label="f2")
_ = plt.legend()
plt.show()
```
Example from the documentation. Sliders are not shown in notebook.

**Actual outcome**
<img src=https://i.imgur.com/WDa15YM.png width=70%>

**Expected outcome**
Sliders should appear above the Figure title. Works with `ipywidgets 7.6.3`.

**Version Info**

  * Matplotlib version: 3.5.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): ipympl
  * Python version: 3.9
  * ipywidgets version: 8.0.1

**Comment by ianhi** [comment]
Hi @jubrau are you sitll having this issue? I can't replicate this with ipywidgets `8.0.2`

I know there were some initial issues with th eipywidgets release, so it's possible that `8.0.2` fixed the issue you were having.

**Comment by jubrau** [comment]
After installing ipywidgets `8.0.2` both in the base conda environment and in the actual environment the bug seems to be gone. Thanks!
