### ISSUE TITLE
NameError: name 'display' is not defined

### ISSUE THREAD

**Issue by havardox** [ianhi/mpl-interactions#256]
Following [this tutorial](https://mpl-interactions.readthedocs.io/en/stable/examples/zoom-factory.html) on the docs gives me the following error:

`NameError: name 'display' is not defined`

What is "display"? What do I need to import/define so "display" will be available in the current namespace?

Here's my exact code (in a non-Jupyter environment):

```python
import matplotlib.pyplot as plt

from mpl_interactions import ioff, panhandler, zoom_factory

image = plt.imread(
    "https://github.com/matplotlib/matplotlib/raw/v3.3.0/lib/matplotlib/mpl-data/sample_data/ada.png"
)

with ioff:
    fig, ax = plt.subplots()
ax.imshow(image)
disconnect_zoom = zoom_factory(ax)
display(fig.canvas)
```

**Comment by ianhi** [comment]
Important caveat: I plan to deprecate this functionality from this package and am now supporting it in the standalone [`mpl-pan-zoom`](https://mpl-pan-zoom.readthedocs.io/en/latest/#) package which I would encourage you to use instead.

`display` is definted by `IPython` and only works in a jupyter context. That tutorial should be updated to say as much or ideally to no use display.



Try using this code:
```python
import matplotlib.pyplot as plt

from mpl_interactions import ioff, panhandler, zoom_factory

image = plt.imread(
    "https://github.com/matplotlib/matplotlib/raw/v3.3.0/lib/matplotlib/mpl-data/sample_data/ada.png"
)


fig, ax = plt.subplots()
ax.imshow(image)
disconnect_zoom = zoom_factory(ax)

plt.show()
```

**Comment by havardox** [comment]
Thanks for the reply! That works
