### ISSUE TITLE
> It would be cool to have interactive_[imshow, pcolormesh, hist,...]. I think these all deserve separate functions as they have different signatures and are different in matplotlib.

### ISSUE THREAD

**Issue by SeanAshley5** [ianhi/mpl-interactions#60]
> It would be cool to have interactive_[imshow, pcolormesh, hist,...]. I think these all deserve separate functions as they have different signatures and are different in matplotlib. 
> 
> 
> 
> First list:
> 
> - [ x] hist
> 
> - [ x] scatter
> 
> - [ x] imshow
> 
> - [ ] pcolormesh
> 
> - [ ] errorbar
> 
> - [ ] seaborn distplot
> 
> 
> 
> each should get their own `interactive_[...]_factory` and `interactive_[...]` function
> 
> 
> 
> Pretty much all of the functions in pyplot could be possibly be included, but the above are probably the most useful.

> - Hist

> - Scatter

__Originally posted by @SeanAshley5 in https://github.com/ianhi/mpl-interactions/issues/59#issuecomment-674457042__

**Comment by ianhi** [comment]
Hi @SeanAshley5 i'm going to close this to keep the tracking of this contained in the other issue. Thanks!

**Comment by SeanAshley5** [comment]
@ianhi no problem bud

**Comment by SeanAshley5** [comment]
> > It would be cool to have interactive_[imshow, pcolormesh, hist,...]. I think these all deserve separate functions as they have different signatures and are different in matplotlib. 
> > 
> > 
> > 
> > First list:
> > 
> > - [ x] hist
> > 
> > - [ x] scatter
> > 
> > - [ x] imshow
> > 
> > - [ ] pcolormesh
> > 
> > - [ ] errorbar
> > 
> > - [ ] seaborn distplot
> > 
> > 
> > 
> > each should get their own `interactive_[...]_factory` and `interactive_[...]` function
> > 
> > 
> > 
> > Pretty much all of the functions in pyplot could be possibly be included, but the above are probably the most useful.
> 
> > - Hist
> 
> > - Scatter
> 
> __Originally posted by @SeanAshley5 in https://github.com/ianhi/mpl-interactions/issues/59#issuecomment-674457042__
