### ISSUE TITLE
array slicer

### ISSUE THREAD

**Issue by ianhi** [ianhi/mpl-interactions#77]
scroll to move along an axis of an array and then imshow it

edit: scroll as option but sliders with play buttons should be the first option see [below](https://github.com/ianhi/mpl-interactions/issues/77#issuecomment-691701886)

**Comment by ianhi** [comment]
or should optionally use a slider

cc: @AdilRabbani I saw your post in the jupyter-widgets gitter channel about this very topic. If you get it working and would like to contribute it here you're more than welcome too :) otherwise I plan on adding this sometime in the next few weeks

**Comment by AdilRabbani** [comment]
Hello @ianhi sorry for the late reply. I would be happy to contribute :) Its just that I've been busy with exams and work and sometimes it gets hard to juggle everything. 😅 Would you be able to give an overview of the repository and where should I be making these changes. I can see that [generic.py](https://github.com/ianhi/mpl-interactions/blob/master/mpl_interactions/generic.py) is the one I should be updating? Also, here is the code for displaying images through a slider:
```
import ipywidgets as widgets
from IPython.display import display, Image, clear_output

def _cycle_images(change, out):
    with out:
        clear_output(wait=True)
        display(Image("images/" + str(change.new) + ".png"))

out = widgets.Output()
        
with out:
    display(Image("images/first_image.png"))
    
display(out)

frame = widgets.IntSlider(
        min=1,
        max=4,
        step=1,
        value=1,
        description="slider value",
    )

def callback(change):
        _cycle_images(change, out)

frame.observe(callback, "value")

display(frame)
```
Note, that I'm using `Image()` and not `imshow()` but that can be used as well. The code isn't really that polished and there might be many improvements that can be done. This was only I could come up with, to just get the work done. 😬

**Comment by ianhi** [comment]
Hi @AdilRabbani no need to apologize! You're really under no obligation to respond to a stranger on the internet mentioning you on a repository you hadn't looked at before lol.

> I would be happy to contribute :) Its just that I've been busy with exams and work and sometimes it gets hard to juggle everything. 

Rad! I definitely understand the busyiness. Somehow there is never enough time  for everything :/

> This was only I could come up with, to just get the work done. grimacing

That's how everything starts! If you look back in time this library started like that. I needed something so I just hacked some nonsense together (see here: https://github.com/ianhi/mpl-interactions/tree/d1b99e344ad8e05644131cb027e49d111b8959f0/jupyter_jukebox)

Your code looks good I'm glad it worked for what you needed! I may have misinterpreted your gitter post though, I thought you were using matplotlib. This library needs to implement this using matplotlib's `imshow` function as it is meant to be an extension of matplotlib. This also has the added benefit of working outside of jupyter notebooks.

Looking at what you're trying to accomplish it actually seems that it would be a better fit for an `interactive_imshow` function. That also needs to be implemented and I'm tracking that over in https://github.com/ianhi/mpl-interactions/issues/59. Of course you're still more than welcome to contribute an `array_slicer` function. To that end here is an overview of the library and a clearer statement of what array_slicer should accomplish. Don't hesitate to ask questions if you have any! (or to disappear completely if you're not interested - no worries if this doesn't fit into your life.)


### Overview of library

[pyplot.py](https://github.com/ianhi/mpl-interactions/blob/master/mpl_interactions/pyplot.py) wraps the `matplotlib.pyplot.*` functions to make it so you can pass a python function and the parameters you want to vary and the plots will update based on the sliders it creates. You can see an example of this on the [first page of the docs](https://mpl-interactions.readthedocs.io/en/latest/#basic-example). There is some useful code in there that detects the matplotlib backend and will either make ipywidgets sliders or matplotlib sliders based on the backend and then also shows how to connect those sliders to an update function. Although the mechanics there are a bit more complex than what array slicer will need because those need to deal with arbitrary parameters and need to interpret user input. In contrast, array-slicer would only need to make `IntSliders` and can just look at the array shape to figure out what sliders it needs to make

[generic.py](https://github.com/ianhi/mpl-interactions/blob/master/mpl_interactions/generic.py) is indeed the correct place for this to go. It contains useful ways to interact with maptlotlib that don't directly map to an existing matplotlib function. 

### What this function should do

I thought a bit more about how this function should work and wrote it down below. Does this call signature make sense to you? i.e. is there anything you think should be different?

```python
# images are expected to have shapes like
# (N, X, Y) or (N1,..., N10, X, Y)
# images are expected to have shapes like
# (N, X, Y) or (N1,..., N10, X, Y)
def array_slicer(arr, ax=None, figsize=None):
    """
    Creates sliders to index an array
    The last two axes of the array must be the image
    
    
    parameters
    ----------
    arr : array-like
        At least 3 dimensional. The final two dimensions are the X and Y dimensions.
    ax : maptlotlib axis, optional
        if None a new figure and axis will be created
    figsize: (float, float), optional
        figsize to use if ax is None

    returns
    -------
    fig : matplotlib figure
    ax : matplotlib axis
    sliders : list of sliders
        Depending on the matplotlib backend these will be 
        either ipywidgets or maptlotlib sliders
    """
    if ax is None:
        fig, ax = plt.subplots(figsize=figsize)
    else:
        fig = ax.get_figure()
    # rest of fnciton 
    # blah blah blah
```

And now an example of how I imagine it being used:
```python
# Create some example image stacks

import numpy as np
parameter1 = np.linspace(-5,5)
parameter2 = np.linspace(-5,5, 25)
x = np.linspace(0,np.pi,200)
y = np.linspace(0,10,200)
X,Y = np.meshgrid(x,y)
image_stack1 = np.sin(X)[None,:,:]+np.exp(np.cos(Y[None,:,:]*parameter1[:,None,None]))
print(f"image_stack1.shape : {image_stack1.shape}")
# image_stack1.shape : (50, 200, 200)

# create another image stack with shape (50, 25, 200, 200)
image_stack2 = np.sin(X)[None,None,:,:]*parameter2[:,None,None] + np.exp(np.cos(Y[None,:,:]*parameter1[:,None,None]))[:,None, ...]
print(f"image_stack2.shape : {image_stack2.shape}")
# image_stack2.shape : (50, 25, 200, 200)




# this should create a plot that imshows the 200x200 images
# and there should be one slider that goes from 0 => 49
array_slicer(image_stack1)

# this should create a plot that imshows the 200x200 images
# and there should be two sliders. One that goes from 0 => 49
# and another right below that goes from 0 => 24
array_slicer(image_stack2)

```

**Comment by ianhi** [comment]
talked to john about this and we decided that all of the following shold be valid call signatures:
```python
array_slicer(arr, axis0 = (0,15), axis1 = (1,56), names = ['t', 'mu'], play=False)
array_slicer(arr, axis0 = (0,15), axis1 = (1,56), names = ['t', 'mu'], play=[True, False])
array_slicer(arr, axes = [('t', (0,15)), ('mu', np.linspace())] )
array_slicer(arr, axes = [('t', (0,15)), None, ('mu', np.linspace())] )
array_slicer(arr)
```
and I'd maybe add this as well:
```python
array_slicer(arr, axes = [('t', (0,15), True), None, ('mu', np.linspace())], play=False )
```
which owuld give only the `t` slider a play widget

**Comment by ianhi** [comment]
for matplotlib sliders I think it will be trickier as they don't take specific values, so we'll need to convert the sliders to return integer values for indexing with `np.round` or something similar

**Comment by ianhi** [comment]
@all-contributors please add @jrussell25 for Documentation
